export interface AchievementDef {
  id: string;
  nameEn: string;
  nameFr: string;
  descEn: string;
  descFr: string;
  icon: string;
}

export const achievements: AchievementDef[] = [
  {
    id: 'first_quiz',
    nameEn: 'First Steps',
    nameFr: 'Premiers Pas',
    descEn: 'Answer your first quiz question',
    descFr: 'R\u00e9ponds \u00e0 ta premi\u00e8re question de quiz',
    icon: '\u{1F476}',
  },
  {
    id: 'points_100',
    nameEn: 'Century Club',
    nameFr: 'Club des Cent',
    descEn: 'Earn 100 points',
    descFr: 'Gagne 100 points',
    icon: '\u{1F4AF}',
  },
  {
    id: 'points_500',
    nameEn: 'Half a Thousand',
    nameFr: 'Cinq Cents',
    descEn: 'Earn 500 points',
    descFr: 'Gagne 500 points',
    icon: '\u{2B50}',
  },
  {
    id: 'points_1000',
    nameEn: 'Grand Sorcerer',
    nameFr: 'Grand Sorcier',
    descEn: 'Earn 1000 points',
    descFr: 'Gagne 1000 points',
    icon: '\u{1F9D9}',
  },
  {
    id: 'wordle_first_win',
    nameEn: 'Word Wizard',
    nameFr: 'Magicien des Mots',
    descEn: 'Win your first Wordle',
    descFr: 'Gagne ton premier Wordle',
    icon: '\u{1F4DD}',
  },
  {
    id: 'wordle_streak_3',
    nameEn: 'Winning Streak',
    nameFr: 'S\u00e9rie Gagnante',
    descEn: 'Win 3 Wordles in a row',
    descFr: 'Gagne 3 Wordles d\u2019affil\u00e9e',
    icon: '\u{1F525}',
  },
  {
    id: 'wordle_streak_5',
    nameEn: 'Unstoppable',
    nameFr: 'Inarr\u00eatable',
    descEn: 'Win 5 Wordles in a row',
    descFr: 'Gagne 5 Wordles d\u2019affil\u00e9e',
    icon: '\u{26A1}',
  },
  {
    id: 'goblet_winner',
    nameEn: 'Fortune Favours',
    nameFr: 'La Fortune Sourit',
    descEn: 'Win the Goblet of Fortune',
    descFr: 'Gagne \u00e0 la Coupe de Fortune',
    icon: '\u{1F3C6}',
  },
  {
    id: 'house_sorted',
    nameEn: 'Sorted!',
    nameFr: 'R\u00e9parti\u00a0!',
    descEn: 'Complete the Sorting Ceremony',
    descFr: 'Termine la C\u00e9r\u00e9monie de R\u00e9partition',
    icon: '\u{1F3E0}',
  },
  {
    id: 'patronus_revealed',
    nameEn: 'Expecto Patronum',
    nameFr: 'Expecto Patronum',
    descEn: 'Discover your Patronus',
    descFr: 'D\u00e9couvre ton Patronus',
    icon: '\u{2728}',
  },
  {
    id: 'potions_first',
    nameEn: 'Apprentice Brewer',
    nameFr: 'Apprenti Brasseur',
    descEn: 'Complete a Potions Class',
    descFr: 'Termine un cours de Potions',
    icon: '\u{2697}\uFE0F',
  },
  {
    id: 'duel_first',
    nameEn: 'Duelist',
    nameFr: 'Duelliste',
    descEn: 'Complete a Spell Duel',
    descFr: 'Termine un Duel de Sorts',
    icon: '\u{2694}\uFE0F',
  },
  {
    id: 'daily_first',
    nameEn: 'Daily Prophet',
    nameFr: 'La Gazette',
    descEn: 'Complete a Daily Challenge',
    descFr: 'Termine un D\u00e9fi du Jour',
    icon: '\u{1F4F0}',
  },
  {
    id: 'perfect_quiz',
    nameEn: 'Outstanding O.W.L.',
    nameFr: 'B.U.S.E. Optimal',
    descEn: 'Get a perfect score on a quiz',
    descFr: 'Obtiens un score parfait \u00e0 un quiz',
    icon: '\u{1F4A0}',
  },
  {
    id: 'all_easy',
    nameEn: 'First Year Graduate',
    nameFr: 'Dipl\u00f4m\u00e9 Premi\u00e8re Ann\u00e9e',
    descEn: 'Complete all easy quizzes',
    descFr: 'Termine tous les quiz faciles',
    icon: '\u{1F393}',
  },
  {
    id: 'all_normal',
    nameEn: 'O.W.L. Scholar',
    nameFr: '\u00c9rudit B.U.S.E.',
    descEn: 'Complete all normal quizzes',
    descFr: 'Termine tous les quiz normaux',
    icon: '\u{1F4DA}',
  },
  {
    id: 'bookworm_5',
    nameEn: 'Bookworm',
    nameFr: 'Rat de Biblioth\u00e8que',
    descEn: 'Complete quizzes from 5 different books',
    descFr: 'Termine des quiz de 5 livres diff\u00e9rents',
    icon: '\u{1F41B}',
  },
  {
    id: 'speed_demon_duel',
    nameEn: 'Quick Draw',
    nameFr: 'Vif comme l\u2019\u00c9clair',
    descEn: 'Win a duel with a perfect score',
    descFr: 'Gagne un duel avec un score parfait',
    icon: '\u{1F4A8}',
  },
  {
    id: 'master_brewer',
    nameEn: 'Master Brewer',
    nameFr: 'Ma\u00eetre Brasseur',
    descEn: 'Complete Potions in under 30 seconds',
    descFr: 'Termine les Potions en moins de 30 secondes',
    icon: '\u{1F9EA}',
  },
  // --- Hard achievements ---
  {
    id: 'points_2500',
    nameEn: 'Legendary Wizard',
    nameFr: 'Sorcier L\u00e9gendaire',
    descEn: 'Earn 2500 points',
    descFr: 'Gagne 2500 points',
    icon: '\u{1F3C6}',
  },
  {
    id: 'points_5000',
    nameEn: 'Order of Merlin',
    nameFr: 'Ordre de Merlin',
    descEn: 'Earn 5000 points',
    descFr: 'Gagne 5000 points',
    icon: '\u{1F396}\uFE0F',
  },
  {
    id: 'all_hard',
    nameEn: 'N.E.W.T. Master',
    nameFr: 'Ma\u00eetre des A.S.P.I.C.',
    descEn: 'Complete all hard quizzes',
    descFr: 'Termine tous les quiz difficiles',
    icon: '\u{1F525}',
  },
  {
    id: 'all_expert',
    nameEn: 'Albus Dumbledore',
    nameFr: 'Albus Dumbledore',
    descEn: 'Complete all expert quizzes',
    descFr: 'Termine tous les quiz expert',
    icon: '\u{1F9D9}\u200D\u2642\uFE0F',
  },
  {
    id: 'perfectionist',
    nameEn: 'Hermione Granger',
    nameFr: 'Hermione Granger',
    descEn: 'Get 3 perfect quiz scores',
    descFr: 'Obtiens 3 scores parfaits aux quiz',
    icon: '\u{1F48E}',
  },
  {
    id: 'wordle_streak_10',
    nameEn: 'Spellbound',
    nameFr: 'Ensorcele\u0301',
    descEn: 'Win 10 Wordles in a row',
    descFr: 'Gagne 10 Wordles d\u2019affil\u00e9e',
    icon: '\u{1F52E}',
  },
  {
    id: 'lightning_brewer',
    nameEn: 'Felix Felicis',
    nameFr: 'Felix Felicis',
    descEn: 'Complete Potions in under 15 seconds',
    descFr: 'Termine les Potions en moins de 15 secondes',
    icon: '\u2697\uFE0F',
  },
  {
    id: 'duel_master',
    nameEn: 'Defence Professor',
    nameFr: 'Professeur de D\u00e9fense',
    descEn: 'Win 10 perfect duels',
    descFr: 'Gagne 10 duels parfaits',
    icon: '\u2694\uFE0F',
  },
  {
    id: 'daily_streak_7',
    nameEn: 'Dedicated Student',
    nameFr: '\u00c9tudiant D\u00e9vou\u00e9',
    descEn: 'Complete daily challenges 7 days in a row',
    descFr: 'Termine les d\u00e9fis du jour 7 jours d\u2019affil\u00e9e',
    icon: '\u{1F4C5}',
  },
  {
    id: 'snitch_catcher',
    nameEn: 'Seeker',
    nameFr: 'Attrapeur',
    descEn: 'Catch 3 Golden Snitches',
    descFr: 'Attrape 3 Vifs d\u2019Or',
    icon: '\u{1F3C5}',
  },
  {
    id: 'dragon_tamer',
    nameEn: 'Dragon Tamer',
    nameFr: 'Dresseur de Dragons',
    descEn: 'Hatch your first dragon egg',
    descFr: 'Fais éclore ton premier œuf de dragon',
    icon: '\u{1F409}',
  },
];
