export interface AchievementDef {
  id: string;
  nameEn: string;
  nameFr: string;
  descEn: string;
  descFr: string;
  icon: string;
}

export const achievements: AchievementDef[] = [
  {
    id: 'first_quiz',
    nameEn: 'First Steps',
    nameFr: 'Premiers Pas',
    descEn: 'Answer your first quiz question',
    descFr: 'R\u00e9ponds \u00e0 ta premi\u00e8re question de quiz',
    icon: '\u{1F476}',
  },
  {
    id: 'points_100',
    nameEn: 'Century Club',
    nameFr: 'Club des Cent',
    descEn: 'Earn 100 points',
    descFr: 'Gagne 100 points',
    icon: '\u{1F4AF}',
  },
  {
    id: 'points_500',
    nameEn: 'Half a Thousand',
    nameFr: 'Cinq Cents',
    descEn: 'Earn 500 points',
    descFr: 'Gagne 500 points',
    icon: '\u{2B50}',
  },
  {
    id: 'points_1000',
    nameEn: 'Grand Sorcerer',
    nameFr: 'Grand Sorcier',
    descEn: 'Earn 1000 points',
    descFr: 'Gagne 1000 points',
    icon: '\u{1F9D9}',
  },
  {
    id: 'wordle_first_win',
    nameEn: 'Word Wizard',
    nameFr: 'Magicien des Mots',
    descEn: 'Win your first Wordle',
    descFr: 'Gagne ton premier Wordle',
    icon: '\u{1F4DD}',
  },
  {
    id: 'wordle_streak_3',
    nameEn: 'Winning Streak',
    nameFr: 'S\u00e9rie Gagnante',
    descEn: 'Win 3 Wordles in a row',
    descFr: 'Gagne 3 Wordles d\u2019affil\u00e9e',
    icon: '\u{1F525}',
  },
  {
    id: 'wordle_streak_5',
    nameEn: 'Unstoppable',
    nameFr: 'Inarr\u00eatable',
    descEn: 'Win 5 Wordles in a row',
    descFr: 'Gagne 5 Wordles d\u2019affil\u00e9e',
    icon: '\u{26A1}',
  },
  {
    id: 'goblet_winner',
    nameEn: 'Fortune Favours',
    nameFr: 'La Fortune Sourit',
    descEn: 'Win the Goblet of Fortune',
    descFr: 'Gagne \u00e0 la Coupe de Fortune',
    icon: '\u{1F3C6}',
  },
  {
    id: 'house_sorted',
    nameEn: 'Sorted!',
    nameFr: 'R\u00e9parti\u00a0!',
    descEn: 'Complete the Sorting Ceremony',
    descFr: 'Termine la C\u00e9r\u00e9monie de R\u00e9partition',
    icon: '\u{1F3E0}',
  },
  {
    id: 'patronus_revealed',
    nameEn: 'Expecto Patronum',
    nameFr: 'Expecto Patronum',
    descEn: 'Discover your Patronus',
    descFr: 'D\u00e9couvre ton Patronus',
    icon: '\u{2728}',
  },
  {
    id: 'potions_first',
    nameEn: 'Apprentice Brewer',
    nameFr: 'Apprenti Brasseur',
    descEn: 'Complete a Potions Class',
    descFr: 'Termine un cours de Potions',
    icon: '\u{2697}\uFE0F',
  },
  {
    id: 'duel_first',
    nameEn: 'Duelist',
    nameFr: 'Duelliste',
    descEn: 'Complete a Spell Duel',
    descFr: 'Termine un Duel de Sorts',
    icon: '\u{2694}\uFE0F',
  },
  {
    id: 'daily_first',
    nameEn: 'Daily Prophet',
    nameFr: 'La Gazette',
    descEn: 'Complete a Daily Challenge',
    descFr: 'Termine un D\u00e9fi du Jour',
    icon: '\u{1F4F0}',
  },
  {
    id: 'perfect_quiz',
    nameEn: 'Outstanding O.W.L.',
    nameFr: 'B.U.S.E. Optimal',
    descEn: 'Get a perfect score on a quiz',
    descFr: 'Obtiens un score parfait \u00e0 un quiz',
    icon: '\u{1F4A0}',
  },
  {
    id: 'all_easy',
    nameEn: 'First Year Graduate',
    nameFr: 'Dipl\u00f4m\u00e9 Premi\u00e8re Ann\u00e9e',
    descEn: 'Complete all easy quizzes',
    descFr: 'Termine tous les quiz faciles',
    icon: '\u{1F393}',
  },
  {
    id: 'all_normal',
    nameEn: 'O.W.L. Scholar',
    nameFr: '\u00c9rudit B.U.S.E.',
    descEn: 'Complete all normal quizzes',
    descFr: 'Termine tous les quiz normaux',
    icon: '\u{1F4DA}',
  },
  {
    id: 'bookworm_5',
    nameEn: 'Bookworm',
    nameFr: 'Rat de Biblioth\u00e8que',
    descEn: 'Complete quizzes from 5 different books',
    descFr: 'Termine des quiz de 5 livres diff\u00e9rents',
    icon: '\u{1F41B}',
  },
  {
    id: 'speed_demon_duel',
    nameEn: 'Quick Draw',
    nameFr: 'Vif comme l\u2019\u00c9clair',
    descEn: 'Win a duel with a perfect score',
    descFr: 'Gagne un duel avec un score parfait',
    icon: '\u{1F4A8}',
  },
  {
    id: 'master_brewer',
    nameEn: 'Master Brewer',
    nameFr: 'Ma\u00eetre Brasseur',
    descEn: 'Complete Potions in under 30 seconds',
    descFr: 'Termine les Potions en moins de 30 secondes',
    icon: '\u{1F9EA}',
  },
];
