export interface Spell {
  name: string;
  effectEn: string;
  effectFr: string;
  wrongEffectsEn: string[];
  wrongEffectsFr: string[];
}

export const spells: Spell[] = [
  {
    name: 'Expelliarmus',
    effectEn: 'Disarms opponent',
    effectFr: "D\u00e9sarme l'adversaire",
    wrongEffectsEn: ['Creates a shield', 'Stuns the target', 'Produces light'],
    wrongEffectsFr: ['Cr\u00e9e un bouclier', 'Stup\u00e9fixe la cible', 'Produit de la lumi\u00e8re'],
  },
  {
    name: 'Lumos',
    effectEn: 'Creates light',
    effectFr: 'Cr\u00e9e de la lumi\u00e8re',
    wrongEffectsEn: ['Disarms opponent', 'Opens locks', 'Levitates objects'],
    wrongEffectsFr: ["D\u00e9sarme l'adversaire", 'Ouvre les serrures', 'Fait l\u00e9viter les objets'],
  },
  {
    name: 'Alohomora',
    effectEn: 'Opens locks',
    effectFr: 'Ouvre les serrures',
    wrongEffectsEn: ['Creates light', 'Summons objects', 'Repairs broken objects'],
    wrongEffectsFr: ['Cr\u00e9e de la lumi\u00e8re', 'Invoque des objets', 'R\u00e9pare les objets cass\u00e9s'],
  },
  {
    name: 'Accio',
    effectEn: 'Summons objects',
    effectFr: 'Invoque des objets',
    wrongEffectsEn: ['Levitates objects', 'Banishes objects', 'Opens locks'],
    wrongEffectsFr: ['Fait l\u00e9viter les objets', 'Fait dispara\u00eetre les objets', 'Ouvre les serrures'],
  },
  {
    name: 'Wingardium Leviosa',
    effectEn: 'Levitates objects',
    effectFr: 'Fait l\u00e9viter les objets',
    wrongEffectsEn: ['Summons objects', 'Creates a shield', 'Makes things fly'],
    wrongEffectsFr: ['Invoque des objets', 'Cr\u00e9e un bouclier', 'Fait voler les choses'],
  },
  {
    name: 'Stupefy',
    effectEn: 'Stuns the target',
    effectFr: 'Stup\u00e9fixe la cible',
    wrongEffectsEn: ['Disarms opponent', 'Kills the target', 'Freezes the target'],
    wrongEffectsFr: ["D\u00e9sarme l'adversaire", 'Tue la cible', 'G\u00e8le la cible'],
  },
  {
    name: 'Protego',
    effectEn: 'Creates a shield',
    effectFr: 'Cr\u00e9e un bouclier',
    wrongEffectsEn: ['Stuns the target', 'Disarms opponent', 'Makes invisible'],
    wrongEffectsFr: ['Stup\u00e9fixe la cible', "D\u00e9sarme l'adversaire", 'Rend invisible'],
  },
  {
    name: 'Expecto Patronum',
    effectEn: 'Conjures a Patronus',
    effectFr: 'Invoque un Patronus',
    wrongEffectsEn: ['Creates a shield', 'Produces light', 'Summons objects'],
    wrongEffectsFr: ['Cr\u00e9e un bouclier', 'Produit de la lumi\u00e8re', 'Invoque des objets'],
  },
  {
    name: 'Obliviate',
    effectEn: 'Erases memories',
    effectFr: 'Efface les souvenirs',
    wrongEffectsEn: ['Reads minds', 'Stuns the target', 'Makes invisible'],
    wrongEffectsFr: ['Lit les pens\u00e9es', 'Stup\u00e9fixe la cible', 'Rend invisible'],
  },
  {
    name: 'Riddikulus',
    effectEn: 'Repels a Boggart',
    effectFr: 'Repousse un \u00c9pouvantard',
    wrongEffectsEn: ['Creates laughter', 'Stuns the target', 'Creates a shield'],
    wrongEffectsFr: ['Provoque le rire', 'Stup\u00e9fixe la cible', 'Cr\u00e9e un bouclier'],
  },
  {
    name: 'Petrificus Totalus',
    effectEn: 'Full body-bind',
    effectFr: 'P\u00e9trifie enti\u00e8rement',
    wrongEffectsEn: ['Stuns the target', 'Freezes the target', 'Disarms opponent'],
    wrongEffectsFr: ['Stup\u00e9fixe la cible', 'G\u00e8le la cible', "D\u00e9sarme l'adversaire"],
  },
  {
    name: 'Impedimenta',
    effectEn: 'Slows the target',
    effectFr: 'Ralentit la cible',
    wrongEffectsEn: ['Freezes the target', 'Stuns the target', 'Full body-bind'],
    wrongEffectsFr: ['G\u00e8le la cible', 'Stup\u00e9fixe la cible', 'P\u00e9trifie enti\u00e8rement'],
  },
  {
    name: 'Reparo',
    effectEn: 'Repairs broken objects',
    effectFr: 'R\u00e9pare les objets cass\u00e9s',
    wrongEffectsEn: ['Destroys objects', 'Summons objects', 'Levitates objects'],
    wrongEffectsFr: ['D\u00e9truit les objets', 'Invoque des objets', 'Fait l\u00e9viter les objets'],
  },
  {
    name: 'Nox',
    effectEn: 'Extinguishes light',
    effectFr: '\u00c9teint la lumi\u00e8re',
    wrongEffectsEn: ['Creates light', 'Creates darkness', 'Makes invisible'],
    wrongEffectsFr: ['Cr\u00e9e de la lumi\u00e8re', "Cr\u00e9e l'obscurit\u00e9", 'Rend invisible'],
  },
  {
    name: 'Sectumsempra',
    effectEn: 'Slashes the target',
    effectFr: 'Lacère la cible',
    wrongEffectsEn: ['Stuns the target', 'Disarms opponent', 'Creates a shield'],
    wrongEffectsFr: ['Stup\u00e9fixe la cible', "D\u00e9sarme l'adversaire", 'Cr\u00e9e un bouclier'],
  },
  {
    name: 'Levicorpus',
    effectEn: 'Dangles target upside down',
    effectFr: 'Suspend la cible la t\u00eate en bas',
    wrongEffectsEn: ['Levitates objects', 'Full body-bind', 'Slows the target'],
    wrongEffectsFr: ['Fait l\u00e9viter les objets', 'P\u00e9trifie enti\u00e8rement', 'Ralentit la cible'],
  },
  {
    name: 'Aguamenti',
    effectEn: 'Produces water',
    effectFr: "Produit de l'eau",
    wrongEffectsEn: ['Creates fire', 'Produces light', 'Creates ice'],
    wrongEffectsFr: ['Cr\u00e9e du feu', 'Produit de la lumi\u00e8re', 'Cr\u00e9e de la glace'],
  },
  {
    name: 'Incendio',
    effectEn: 'Creates fire',
    effectFr: 'Cr\u00e9e du feu',
    wrongEffectsEn: ['Produces water', 'Creates light', 'Causes an explosion'],
    wrongEffectsFr: ["Produit de l'eau", 'Produit de la lumi\u00e8re', 'Provoque une explosion'],
  },
  {
    name: 'Silencio',
    effectEn: 'Silences the target',
    effectFr: 'R\u00e9duit la cible au silence',
    wrongEffectsEn: ['Stuns the target', 'Erases memories', 'Makes invisible'],
    wrongEffectsFr: ['Stup\u00e9fixe la cible', 'Efface les souvenirs', 'Rend invisible'],
  },
  {
    name: 'Confundo',
    effectEn: 'Confuses the target',
    effectFr: 'Embrouille la cible',
    wrongEffectsEn: ['Erases memories', 'Stuns the target', 'Reads minds'],
    wrongEffectsFr: ['Efface les souvenirs', 'Stup\u00e9fixe la cible', 'Lit les pens\u00e9es'],
  },
  {
    name: 'Episkey',
    effectEn: 'Heals minor injuries',
    effectFr: 'Soigne les blessures l\u00e9g\u00e8res',
    wrongEffectsEn: ['Repairs broken objects', 'Creates a shield', 'Removes curses'],
    wrongEffectsFr: ['R\u00e9pare les objets cass\u00e9s', 'Cr\u00e9e un bouclier', 'Supprime les mal\u00e9dictions'],
  },
  {
    name: 'Finite Incantatem',
    effectEn: 'Stops ongoing spells',
    effectFr: 'Arr\u00eate les sorts en cours',
    wrongEffectsEn: ['Creates a shield', 'Disarms opponent', 'Removes curses'],
    wrongEffectsFr: ['Cr\u00e9e un bouclier', "D\u00e9sarme l'adversaire", 'Supprime les mal\u00e9dictions'],
  },
  {
    name: 'Sonorus',
    effectEn: 'Amplifies the voice',
    effectFr: 'Amplifie la voix',
    wrongEffectsEn: ['Silences the target', 'Creates a loud bang', 'Erases memories'],
    wrongEffectsFr: ['R\u00e9duit la cible au silence', 'Cr\u00e9e une forte d\u00e9tonation', 'Efface les souvenirs'],
  },
  {
    name: 'Diffindo',
    effectEn: 'Cuts or tears objects',
    effectFr: 'Coupe ou d\u00e9chire les objets',
    wrongEffectsEn: ['Repairs broken objects', 'Destroys objects', 'Slashes the target'],
    wrongEffectsFr: ['R\u00e9pare les objets cass\u00e9s', 'D\u00e9truit les objets', 'Lac\u00e8re la cible'],
  },
  {
    name: 'Engorgio',
    effectEn: 'Enlarges an object',
    effectFr: 'Agrandit un objet',
    wrongEffectsEn: ['Shrinks an object', 'Levitates objects', 'Summons objects'],
    wrongEffectsFr: ['R\u00e9tr\u00e9cit un objet', 'Fait l\u00e9viter les objets', 'Invoque des objets'],
  },
  {
    name: 'Reducio',
    effectEn: 'Shrinks an object',
    effectFr: 'R\u00e9tr\u00e9cit un objet',
    wrongEffectsEn: ['Enlarges an object', 'Destroys objects', 'Makes invisible'],
    wrongEffectsFr: ['Agrandit un objet', 'D\u00e9truit les objets', 'Rend invisible'],
  },
  {
    name: 'Aparecium',
    effectEn: 'Reveals hidden writing',
    effectFr: "R\u00e9v\u00e8le l'\u00e9criture cach\u00e9e",
    wrongEffectsEn: ['Makes invisible', 'Creates light', 'Opens locks'],
    wrongEffectsFr: ['Rend invisible', 'Cr\u00e9e de la lumi\u00e8re', 'Ouvre les serrures'],
  },
  {
    name: 'Colloportus',
    effectEn: 'Seals a door',
    effectFr: 'Scelle une porte',
    wrongEffectsEn: ['Opens locks', 'Creates a shield', 'Repairs broken objects'],
    wrongEffectsFr: ['Ouvre les serrures', 'Cr\u00e9e un bouclier', 'R\u00e9pare les objets cass\u00e9s'],
  },
  {
    name: 'Locomotor Mortis',
    effectEn: 'Locks the legs together',
    effectFr: 'Bloque les jambes',
    wrongEffectsEn: ['Full body-bind', 'Slows the target', 'Stuns the target'],
    wrongEffectsFr: ['P\u00e9trifie enti\u00e8rement', 'Ralentit la cible', 'Stup\u00e9fixe la cible'],
  },
  {
    name: 'Prior Incantato',
    effectEn: 'Shows last spell cast by a wand',
    effectFr: "R\u00e9v\u00e8le le dernier sort d'une baguette",
    wrongEffectsEn: ['Stops ongoing spells', 'Erases memories', 'Reveals hidden writing'],
    wrongEffectsFr: ['Arr\u00eate les sorts en cours', 'Efface les souvenirs', "R\u00e9v\u00e8le l'\u00e9criture cach\u00e9e"],
  },
];
